### ISSUE TITLE
Windows authentication?

### ISSUE THREAD

**Issue by countnazgul** [qlik-oss/corectl#439]
I know that this is not part of the engine but what do you think should be approach when the  authentication is Windows (when inside the domain and outside)?

**Comment by wennmo** [comment]
Hi @countnazgul,
Since there is no support for NTLM authentication in `corectl` you either need to go with certificates or JWT authentication.

If you are outside of the domain or connecting against a multinode environment then JWT header authentication through the proxy is probably preferred.

There is an example in the `enigma.js` repo with information/links on how to set up JWT authentication on Qlik Sense Enterprise for Windows [here](https://github.com/qlik-oss/enigma.js/blob/master/examples/authentication/sense-using-jwt/README.md).

Did that answer your question?

**Comment by countnazgul** [comment]
Yep. Makes perfect sense.

I was expecting this answer but had to to ask :)
