### ISSUE TITLE
Approving and publishing objects via corectl

### ISSUE THREAD

**Issue by RomanYamp** [qlik-oss/corectl#458]
Facing an issue:
When building app jsons into existing published app, objects are not published and not approved. Is it possible to approve it via corectl?

For example the comand would be: corectl app <id> dimensions --approve true

Or something like that?
As for me, it would be a great enhancement for server side enviroments.

**Comment by wennmo** [comment]
Hi @RomanYamp, thanks for the feature request. The publishing flow is not something that we are planning to support in `corectl` at the moment. Basically a published app is not something that should be edited, and instead it should be duplicated -> edited -> republished.

This type of flow would also require more product specific logic, since publishing of apps does not only involve the engine.

**Comment by RomanYamp** [comment]
Hi @wennmo.
Thank you for the fast reply!
Understood your point, there are some other ways to achive my use cases, will go those ways.
Thanks, regards!

**Comment by wennmo** [comment]
Great that you can achieve that flow in some other way, and if you have other ideas that could fit good into `corectl` just file an issue.

Closing this issue since this not something that will be implemented in `corectl` for now.
