### ISSUE TITLE
Add support for generic objects

### ISSUE THREAD

**Issue by sublibra** [qlik-oss/corectl#63]
Add support for listing, getting object content and creating generic objects through the tool.

# Sample design
## Listing objects
`corectl objects`
output
`ID      Type
AF0D  barchart
4AD4  listbox`

## Getting object content
`corectl object <id>`
output
`
{
    <properties of object>
}
`

## Creating and updating objects
By setting the --objects flag objects in the app can be updated

*--objects*
The *--objects flag* is used to specify a list of objects to be set in the app. It can either be used as a parameter to the reload command, or the special update-objects command that does just that.
`corectl --objects=/path/to/genericobject1.json:/path/to/genericobject2.json reload`
`corectl --objects=/path/to/genericobject1.json:/path/to/genericobject2.json update-objects`

**Comment by peol** [comment]
Not sure I agree with it being connected to the `reload` command, I'd prefer to keep these separate otherwise we might end up with one command and 50 arguments to it instead of delivering entry commands that does what the naming suggests.

Having a command and an argument (`objects` and `--objects`) might be confusing.

Also, it would be nice if the syntax was glob-based which is a de-facto standard nowadays (i.e. `corectl --objects="/path/to/objects/*.json"`, `corectl --objects="/path1/genericobject*.json,/path2/genericobject*.json`), there should be go libs to support this expansion.
